helloworld/urls.py
from django.urls.conf import include
from django.contrib import admin
from django.urls import path
from .views import Helloworld

#Contém a lista de roteamentos de URLs
urlpatterns = [
	
	#Index
	#path('', IndexTemplateView.as_view(), name = 'index'),

	path('', Helloworld.index, name = 'index'),

	#Inclui as URLs do app 'website'
	path('', include('website.urls', namespace = 'website')),

	#Interface administrativa
	path('admin/', admin.site.urls),
]

website/urls.py
#URLconf app 'website'

#Importação do arquivo de views
from django.urls import path
from .views import *

app_name = 'website'

# Contém a lista de roteamentos de URLs
urlpatterns = [

	# listar os funcionários
	path(
		'funcionarios/', 
		FuncionarioListView.as_view(), 
		name = 'lista_funcionarios'
	),

	# Atualizar funcionário
	# Buscar pelo {id}
	path(
		'funcionario/<pk>',
		FuncionarioUpdateView.as_view(),
		name = 'atualiza_funcionario'
	),
	# Buscar pelo {slug}
	path(
		'funcionario/<slug>',
		FuncionarioUpdateView.as_view(),
		name = 'atualiza_funcionario'
	),

	# Deletar funcionário
	path(
		'funcionario/excluir/<pk>',
		FuncionarioDeleteView.as_view(),
		name = 'deleta_funcionario'
	),

	# Cadastro funcionario
	path(
		'funcionario/cadastrar/',
		FuncionarioCreateView.as_view(),
		name = 'cadastra_funcionario'
	),

	#Login
	path(
		'form-login/',
		UserAuth.form_login,
		name = 'form_login'
	),

	#Login
	path(
		'login/',
		UserAuth.login,
		name = 'login'
	),

	#Logout
	path(
		'logout/',
		UserAuth.logout,
		name = 'logout'
	),
]

website/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Usuário generico
class User(AbstractUser):
	pass

class Funcionario(models.Model):

	nome = models.CharField(
		max_length = 255,
		null = False,
		blank = False
	)

	sobrenome = models.CharField(
		max_length = 255,
		null = False,
		blank = False
	)

	cpf = models.CharField(
		max_length = 14,
		null = False,
		blank = False
	)

	tempo_de_servico = models.IntegerField(
		default = 0,
		null = False,
		blank = False
	)

	remuneracao = models.DecimalField(
		max_digits = 8,
		decimal_places = 2,
		null = False,
		blank = False
	)

	objetos = models.Manager()

website/forms.py
#Definindo a estrutura do Formulário do Funcionário

from django import forms
from .models import Funcionario

class InsereFuncionarioForm(forms.ModelForm):

	#Campos adicionais

	"""
	chefe = forms.BooleanField(label = 'Chefe?', required = True)

	biografia = forms.CharField(
		label = 'Biografia',
		required = False,
		widget = forms.Textarea
	)
	"""


	#Definição dos campos que serão mostrados no formulário
	class Meta:

		#Modelo base
		model = Funcionario

		#Campos que estarão no formulário
		fields = [
			'nome',
			'sobrenome',
			'cpf',
			'tempo_de_servico',
			'remuneracao',

		]
		#Campos que não estarão no formulário
		exclude = [
			
		]



"""
class InsereFuncionarioForm(forms.form):

	#Campo nome
	nome = forms.CharField(required = True, max_length = 255)
	#Campo sobrenome
	sobrenome = forms.CharField(required = True, max_length = 255)
	#Campo cpf
	cpf = forms.CharField(required = True, max_length = 14)
	#Campo tempo de serviço
	tempo_de_servico = forms.IntegerField(required = True)
	#Campo remuneração
	remuneracao = forms.DecimalField()
"""

helloworld/views.py
from django.conf import settings
from django.shortcuts import redirect, render

#from django.views.generic.base import TemplateView

#Class based Views - index
'''
class IndexTemplateView(TemplateView):

	#Nome do template que será utilizado
	template_name = 'website/index.html'

'''

# Méthodo simples para Index

class Helloworld:

	def index(request):

		# Verifica se não existe um usuário autenticado
		if not request.user.is_authenticated :
			return redirect('%s?next=%s' % (settings.LOGIN_URL, request.path))

		return render(request, 'website/index.html')

website/views.py
#libs
from django.views.generic.edit import UpdateView, DeleteView
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
# Usado em class para o requerimento de login
from django.contrib.auth.mixins import LoginRequiredMixin 
from django.views.generic.list import ListView
from django.shortcuts import render, redirect
from django.views.generic import CreateView
from django.urls import reverse_lazy
from django.conf import settings

#Model
from .models import Funcionario
#Form
from .forms import InsereFuncionarioForm



# Class based Views - lista os funcionarios
class FuncionarioListView(LoginRequiredMixin, ListView):

	# Definição do URL para o template de login
	login_url = settings.LOGIN_URL

	# Depois de efetuar redireciona para o template de FuncionarioListView
	redirect_field_name = 'website:lista_funcionarios'

	# Nome do template que será utilizado
	template_name = 'website/lista.html'
	# Definição do modelo
	model = Funcionario
	"""
		Nome do contexto - array associativo com valores dos atributos
		do modelo funcionario.
	"""
	context_object_name = 'funcionarios'
		


# Class based Views - Atualizar um fucionário
class FuncionarioUpdateView(LoginRequiredMixin, UpdateView):

	# Definição do URL para o template de login
	login_url = settings.LOGIN_URL

	# Depois de efetuar redireciona para o template de FuncionarioUpdateView
	redirect_field_name = 'website:lista_funcionarios'

	# Nome do template que será utilizado
	template_name = 'website/atualiza.html'
	# Definição do modelo
	model = Funcionario

	# Definir os campos para atualizar
	fields = '__all__'

	success_url = reverse_lazy('website:lista_funcionarios')

	def get_object(self, queryset = None):

		funcionario = None

		# Os campos {pk} e {slug} estão presentes em self.kwargs

		pk = self.kwargs.get(self.pk_url_kwarg)

		slug = self.kwargs.get(self.slug_url_kwarg)

		if pk is not None :
			# Busca o funcionário apartir do id
			funcionario = Funcionario.objetos.filter(id = pk).first()

		elif slug is not None :
			# Pega o campo slub do Model
			campo_slug = self.get_slug_field()

			# Busca o funcionario apartir do slug
			funcionario = Funcionario.objetos.filter(**{campo_slug : slug}).first()

		return funcionario


# Class based Views - Informações de um fucionário
class FuncionarioDeleteView(LoginRequiredMixin, DeleteView):

	# Definição do URL para o template de login
	login_url = settings.LOGIN_URL

	# Depois de efetuar redireciona para o template de FuncionarioDeleteView
	redirect_field_name = 'website:lista_funcionarios'

	# Nome do template que será utilizado
	template_name = 'website/exclui.html'
	# Definição do modelo
	model = Funcionario
	"""
		Nome do contexto - array associativo com valores dos atributos
		do modelo funcionario.
	"""
	context_object_name = 'funcionario'
	# Caso a delação for bem sucedida, redireciona para o template 'lista_funcionarios'
	success_url = reverse_lazy('website:lista_funcionarios')


# Class based Views - Cadastro de um fucionário
class FuncionarioCreateView(LoginRequiredMixin, CreateView):

	# Definição do URL para o template de login
	login_url = settings.LOGIN_URL
	
	# Depois de efetuar redireciona para o template de FuncionarioCreateView
	redirect_field_name = 'website:cadastra_funcionario'

	# Nome do template que será utilizado
	template_name = 'website/cria.html'
	# Definição do modelo
	model = Funcionario
	# Class Form que contém a estrutura dos campos de funcionario
	form_class = InsereFuncionarioForm
	# Caso o cadastro for bem sucedido, redireciona para o template 'lista_funcionarios'
	success_url = reverse_lazy('website:lista_funcionarios')

	


# Autenticação
class UserAuth:

	def form_login(request):
		return render(request, 'website/login.html')

	def login(request):
			
		# Coleta os dados via POST
		username = request.POST['username']
		password = request.POST['password']

		# Autentica o usuário
		user = authenticate(request, username = username, password = password)

		#Verifica se a variavel 'user' contém um Objeto User
		if user is not None :
			# Efetua o login na aplicação e redireciona para index
			login(request, user)
			return redirect('index');
		else:
			return render(request, 'website/login.html', { 
				'error' : 'Username ou password incorreto !' 
			})

	
	@login_required # Decorador login requerido
	def logout(request):
		# Efetua o logout do Usuário
		logout(request)
		return redirect('index')

website/templates/website/_layout/template-base.html
<!-- Carregando Tag 'tempo_atual' -->
{% load tempo_atual %}

<!DOCTYPE html>
<html>
<head>
	<title>{% block title %}Funcionários {% endblock %}</title>

	<!-- UIkit CSS -->
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.4/css/uikit.min.css" />

</head>
<body>

	<nav class="uk-navbar-container uk-margin" uk-navbar>
	    <div class="uk-navbar-left">
	        <ul class="uk-navbar-nav">
	            <li class="uk-active">
	            	<a href="{% url 'index' %}"> Início </a>
	            </li>
	            {% if user.is_authenticated %}
	            <li class="uk-parent">
	            	<a href="{% url 'website:lista_funcionarios' %}"> Funcionários </a>
	            </li>
	      		{% endif %}
	        </ul>
	    </div>
	     <div class="uk-navbar-right">
	     	<ul class="uk-navbar-nav">
		    	<!-- <li class="uk-parent">
		        	<a href="#"> Horas: {% tempo_atual %} </a>
		        </li> -->
		        {% if user.is_authenticated %}
			        <li class="uk-parent">
		            	<a href="{% url 'website:logout' %}"> Logout </a>
		            </li>
		        {% else %}
			        <li class="uk-parent">
		            	<a href="{% url 'website:form_login' %}"> Login </a>
		            </li>
	            {% endif %}
	     	</ul>
	     </div>
	</nav>

	{% block conteudo %}
	{% endblock %}

	<!-- UIkit JS -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.4/js/uikit.min.js"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.1.4/js/uikit-icons.min.js"></script>
</body>
</html>

website/templates/website/atualiza.html
<!-- Extende do template base --> 
{% extends "website/_layout/template-base.html" %}

<!-- Widget de Formulário -->
{% load widget_tweaks %}

<!-- Bloco que define o title da página -->
{% block title %}
	Editar Funcionário
{% endblock %}

<!-- Conteudo -->
{% block conteudo %}
	<div class="uk-container">

		<form method="post">

			{% csrf_token %}

			<div class="uk-margin">
				
				<label class="uk-form-label" for="{{ form.nome.id_for_label }}">
					Nome:
				</label>
			
				{% render_field form.nome class+="uk-input" %}
				
			</div>

			<div class="uk-margin">
				
				<label class="uk-form-label" for="{{ form.sobrenome.id_for_label }}">
					Sobrenome:
				</label>
			
				{% render_field form.sobrenome class+="uk-input" %}

			</div>

			<div class="uk-margin">
				
				<label class="uk-form-label" for="{{ form.cpf.id_for_label }}">
					CPF:
				</label>
			
				{% render_field form.cpf class+="uk-input" %}

			</div>

			<div class="uk-margin">
				
				<label class="uk-form-label" for="{{ form.tempo_de_servico.id_for_label }}">
					Tempo de Serviço:
				</label>
			
				{% render_field form.tempo_de_servico class+="uk-input" %}

			</div>

			<div class="uk-margin">

				<label class="uk-form-label" for="{{ form.remuneracao.id_for_label }}">
					Remuneração:
				</label>
			
				{% render_field form.remuneracao class+="uk-input" %}

			</div>

			<div class="uk-margin">
				<button class="uk-button uk-button-primary" type="submit">Salvar Dados</button>
			</div>
		</form>
	</div>

{% endblock %}

website/templates/website/cria.html
<!-- Extende do template base --> 
{% extends "website/_layout/template-base.html" %}

<!-- Widget de Formulário -->
{% load widget_tweaks %}

<!-- Bloco que define o title da página -->
{% block title %}
	Cadastro de Funcionário
{% endblock %}

<!-- Conteudo -->
{% block conteudo %}
	<div class="uk-container">

		<form method="post">

			{% csrf_token %}

			<div class="uk-margin">
				
				<label class="uk-form-label" for="{{ form.nome.id_for_label }}">
					Nome:
				</label>
			
				{% render_field form.nome class+="uk-input" %}
				
			</div>

			<div class="uk-margin">
				
				<label class="uk-form-label" for="{{ form.sobrenome.id_for_label }}">
					Sobrenome:
				</label>
			
				{% render_field form.sobrenome class+="uk-input" %}

			</div>

			<div class="uk-margin">
				
				<label class="uk-form-label" for="{{ form.cpf.id_for_label }}">
					CPF:
				</label>
			
				{% render_field form.cpf class+="uk-input" %}

			</div>

			<div class="uk-margin">
				
				<label class="uk-form-label" for="{{ form.tempo_de_servico.id_for_label }}">
					Tempo de Serviço:
				</label>
			
				{% render_field form.tempo_de_servico class+="uk-input" %}

			</div>

			<div class="uk-margin">

				<label class="uk-form-label" for="{{ form.remuneracao.id_for_label }}">
					Remuneração:
				</label>
			
				{% render_field form.remuneracao class+="uk-input" %}

			</div>

			<div class="uk-margin">
				<button class="uk-button uk-button-primary" type="submit">Salvar Dados</button>
			</div>
		</form>
	</div>

{% endblock %}

website/templates/website/exclui.html
<!-- Extende do template base --> 
{% extends "website/_layout/template-base.html" %}


<!-- Bloco que define o title da página -->
{% block title %}
	Remover Funcionário
{% endblock %}

<!-- Conteudo -->
{% block conteudo %}
	<div class="uk-container">
		
		<div class="uk-column-1-1 uk-margin">
			<div class="uk-card uk-card-default uk-card-body uk-width-1-1@m">
			    <h3 class="uk-card-title">Remover - {{ funcionario.nome }} {{ funcionario.sobrenome }}</h3>
			    <p>Realmente deseja remover este funcionário da sua lista ?</p>
				<form method="post">
						{% csrf_token %}			

						<button type="button" class="uk-button uk-button-secondary uk-button-small">
							<a href="{% url 'website:lista_funcionarios' %}" style="color:white;"> Cancelar </a>
						</button>
						<button class="uk-button uk-button-danger uk-button-small">Excluir</button>
				</form>
			</div>
		</div>
		
	</div>
{% endblock %}

website/templates/website/index.html
<!-- Extende do template base --> 
{% extends "website/_layout/template-base.html" %}

<!-- Bloco que define o title da página -->
{% block title %}
	Página Inicial
{% endblock %}

<!-- Bloco de conteúdo da página -->
{% block conteudo %}

<div class="uk-container">
	
	<div class="uk-column-1-1 uk-margin">
		
		<div class="uk-card uk-card-default uk-card-body uk-width-1-1@m">
		    <h3 class="uk-card-title">Cadastrar Funcionário</h3>
		    <p>Cadastre um novo <b>Funcionário</b></p>
		    <a class="uk-button uk-button-default" href="{% url 'website:cadastra_funcionario' %}">
		    	Novo Funcionário
		    </a>
		</div>

	</div>

	<div class="uk-column-1-1">

		<div class="uk-card uk-card-default uk-card-body uk-width-1-1@m">
		    <h3 class="uk-card-title">Lista de Funcionários</h3>
		    <p>Aqui você ver todos os <b>Funcionários</b> já cadastrados</p>
		    <a class="uk-button uk-button-default" href="{% url 'website:lista_funcionarios' %}">
		    	Funcionários
		    </a>
		</div>
	</div>
	
</div>

{% endblock %}

website/templates/website/lista.html
<!-- Extende do template base --> 
{% extends "website/_layout/template-base.html" %}

<!-- Carrega o filtro 'primeira_letra' -->
{% load primeira_letra %}

<!-- Bloco que define o title da página -->
{% block title %}
	Lista de Funcionários
{% endblock %}

{% block conteudo %}
	<div class="uk-container">
		
		<table class="uk-table uk-table-striped">
			<thead>
				<tr>
					<th>#</th>
					<th>Nome</th>
					<th>Sobrenome</th>
					<th>CPF</th>
					<th>Tempo de Serviço</th>
					<th>Remuneração</th>
					<th>Opções</th>
				</tr>
			</thead>
			<tbody>
				<!-- Verifica se existe tuplas no modelo -->
				{% if funcionarios|length > 0 %}
					{% for func in funcionarios %}
					<tr>
						<td><strong>{{ func.nome|primeira_letra }}</strong></td>
						<td>{{ func.nome }}</td>
						<td>{{ func.sobrenome }}</td>
						<td>{{ func.cpf }}</td>
						<td>{{ func.tempo_de_servico }}</td>
						<td>{{ func.remuneracao }}</td>
						<td>
							<a class="uk-button uk-button-secondary uk-button-small" 
							href="{% url 'website:atualiza_funcionario' pk=func.id %}">
								Editar
							</a>
							<a class="uk-button uk-button-danger uk-button-small"
							href="{% url 'website:deleta_funcionario' pk=func.id %}">
								Remover
							</a>
						</td>
					</tr>
					{% endfor %}
				{% else %}
				<tr>
					<td>-</td>
					<td>-</td>
					<td>-</td>
					<td>-</td>
					<td>-</td>
					<td>-</td>
					<td>-</td>
				</tr>
				{% endif %}
				
			</tbody>
		</table>

		<div class="uk-margin">
			<a class="uk-button uk-button-default uk-button-small"
			href="{% url 'website:cadastra_funcionario' %}">
				Novo Funcionário
			</a>
		</div>
	</div>
{% endblock %}

website/templates/website/login.html
<!-- Extende do template base --> 
{% extends "website/_layout/template-base.html" %}

{% block title %}
	Login
{% endblock %}

{% block conteudo %}
	<div class="uk-flex uk-flex-center">
		<div class="uk-card uk-card-default uk-card-body">
			
			{% if error != None %}
				<p class="uk-text-danger">{{ error }}</p>	
			{% endif %}
			
			<form action="{% url 'website:login' %}" method="post">
			    <fieldset class="uk-fieldset">

			        <legend class="uk-legend">Log in</legend>
			       	
			       	{% csrf_token %}
			        
			        <div class="uk-margin">
			            <input class="uk-input" type="text" placeholder="Username" name="username">
			        </div>

			         <div class="uk-margin">
			            <input class="uk-input" type="password" placeholder="Password" name="password">
			        </div>

			        <button class="uk-button uk-button-primary"> Enter </button>

			    </fieldset>
			</form>
		</div>
	</div>
{% endblock %}